language: python
python:
  - "2.7"
install:
  - pip install pyyaml
script:
  - ./check_packages.py
branches:
  only:
  - gh-pages  # Need to enable gh-pages explicitly.
  - /(.*)/
sudo: false  # Use container-based infrastructure for faster builds.
